language: python
python:
    - 3.6
    - 3.5
    - 3.4
sudo: false
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install git+git://github.com/ipython/ipython.git#egg=ipython
    - pip install -f travis-wheels/wheelhouse --pre -e . coveralls
    - python -m ipykernel.kernelspec --user
script:
    - nosetests --with-coverage --cover-package=jupyter_console jupyter_console
after_success:
    - coveralls
